export const QUOTES: string[] = [
  "Your excuses have a perfect attendance record.",
  "Nobody is coming to save you. Good. You never needed saving — you needed to move.",
  "Comfort is a debt. You're paying interest on it right now.",
  "You don't lack time. You lack urgency.",
  "The version of you that keeps waiting for motivation isn't coming either.",
  "Discipline is just a promise you keep when nobody's checking.",
  "You've survived every excuse you've ever made. None of them built anything.",
  "Tired is not the same as done. Sit down when you're done.",
  "The plan doesn't need to be perfect. It needs to start today.",
  "Every day you skip is a vote for who you don't want to become.",
  "Stop negotiating with the version of you that wants to quit.",
  "You already know what needs to happen. Go do the thing you're avoiding.",
  "Small and consistent beats big and abandoned, every single time.",
  "Nobody remembers the day you almost started.",
  "The work doesn't care how you feel about it. Show up anyway.",
  "Momentum is earned in the fifteen minutes you didn't want to give it.",
  "You are what you repeat, not what you intend.",
  "Quit rehearsing the comeback and start the work that makes it true.",
  "The gap between who you are and who you want to be is closed one rep at a time.",
  "Being busy and being disciplined are not the same thing.",
  "You don't need a better mood. You need a lower bar for starting.",
  "Regret is expensive. Discipline is just uncomfortable.",
  "Whatever you're avoiding is exactly what's worth doing first.",
  "Future you is watching. Don't embarrass them.",
  "The streak you're proud of started on a day you didn't feel like it.",
  "Talent is optional. Showing up isn't.",
  "You don't rise to the occasion. You fall to the level of what you've practiced.",
  "There is no finish line waiting for the version of you that keeps stalling.",
  "Stop asking if you're ready. Readiness is a byproduct of starting.",
  "The excuse sounds reasonable. It's still an excuse.",
  "One honest hour beats a week of good intentions.",
  "You're not behind. You're just still deciding to start.",
  "Effort compounds in silence, long before anyone notices.",
  "The hardest rep is the one that gets you off the bench.",
  "Nothing changes on the day you plan to change. It changes on the day you act.",
  "You don't need permission to take this seriously.",
  "Willpower is a muscle you're currently choosing not to use.",
  "The person you're becoming is built in the moments no one applauds.",
  "Stop waiting for it to feel easy. It gets easier after you start, not before.",
  "You can be tired and still be the one who showed up.",
  "Every rep you skip, someone else takes.",
  "You don't need a new plan. You need to run the one you already have.",
  "Discomfort now is cheaper than regret later.",
  "The only workout that doesn't count is the one you didn't do.",
  "Stop auditioning for a life you could just build.",
  "You are allowed to start messy. You are not allowed to not start.",
  "The excuses are getting more creative. The results are not.",
  "Nobody's handing out trophies for almost.",
  "You've already wasted more time deciding than the task would've taken.",
  "The version of you that wins isn't smarter. They're just still in the fight.",
  "Progress doesn't ask for your mood. It asks for your hands.",
  "Do it scared, do it tired, do it imperfect — just do it today.",
  "You keep saying tomorrow. Tomorrow keeps becoming today.",
  "The bar you keep lowering is the ceiling you'll eventually hit.",
  "Consistency is unglamorous. So is everything worth having.",
  "You're not stuck. You're stalling, and you know the difference.",
  "The best time was yesterday. The next best time is in the next five minutes.",
  "Stop waiting for certainty. Certainty is for people who already quit trying.",
  "Your comfort zone has never once produced the person you want to become.",
  "The gap closes one uncomfortable choice at a time — make it now.",
  "You don't need to feel ready. You need to stop asking.",
];

function dayOfYear(date: Date): number {
  const start = new Date(date.getFullYear(), 0, 0);
  const diff = date.getTime() - start.getTime();
  return Math.floor(diff / 86_400_000);
}

export function getDailyQuote(date: Date): string {
  const idx = dayOfYear(date) % QUOTES.length;
  return QUOTES[idx];
}
